filter-by-commitish: true
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
exclude-labels:
  - 'automated-pr'
  - 'dev-work'
  - 're-fix-pr'
template: |
  ## What’s Changed

  $CHANGES
